# Generated by Django 3.1 on 2020-09-17 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0003_auto_20200902_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices_type',
            field=models.CharField(choices=[('t', 'Text field'), ('c', 'Multiple'), ('r', 'Single')], default='r', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
