# Generated by Django 3.1 on 2020-09-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200917_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='polls'),
        ),
    ]
