# Generated by Django 3.1 on 2020-10-07 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_auto_20200917_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices_type',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_type',
            field=models.CharField(choices=[('t', 'Text field'), ('c', 'Multiple'), ('r', 'Single')], default='r', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.ManyToManyField(related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='polls/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=30),
        ),
    ]
