# Generated by Django 3.1 on 2020-10-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20201007_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_type',
        ),
        migrations.AddField(
            model_name='question',
            name='choice_type',
            field=models.CharField(choices=[('t', 'Text field'), ('c', 'Multiple'), ('r', 'Single')], default='r', max_length=2),
        ),
    ]
