# Generated by Django 3.1 on 2020-10-14 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20201013_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='polls/'),
            preserve_default=False,
        ),
    ]
