# Generated by Django 3.1 on 2020-10-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20201014_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='p/media/o/media/l/media/l/media/s/media//'),
        ),
    ]
