# Generated by Django 3.1 on 2020-10-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20201015_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='publish_date',
        ),
    ]
