# Generated by Django 3.1 on 2020-10-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_remove_choice_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_type',
            field=models.CharField(choices=[(0, 'Text field'), (1, 'Multiple'), (2, 'Single')], default=2, max_length=2),
        ),
    ]
